# Generated by Django 4.1.4 on 2023-01-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(blank=True)),
                ("updated_at", models.DateTimeField(blank=True)),
            ],
            options={
                "db_table": "UsersTable",
            },
        ),
    ]
