# Generated by Django 4.1.4 on 2023-01-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
