# Generated by Django 4.1.4 on 2023-01-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
