# Generated by Django 4.1.4 on 2023-01-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cast",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("dob", models.DateField()),
            ],
            options={
                "db_table": "CastsTable",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("runtime", models.IntegerField()),
                ("language", models.CharField(max_length=255)),
                ("tagline", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "MoviesTable",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("email", models.CharField(max_length=255)),
                ("created_at", models.BigIntegerField()),
                ("expiry_at", models.BigIntegerField()),
            ],
            options={
                "db_table": "SessionsTable",
            },
        ),
    ]
