# Generated by Django 4.1.4 on 2023-01-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_cast_movie_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
