# Generated by Django 4.1.4 on 2023-01-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_cast_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="movieid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cast",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
